### ISSUE TITLE
Windows Negfix8 script Link on README is broken. 

### ISSUE THREAD

**Issue by martinjmartinez** [alibosworth/pakon-planar-raw-converter#24] opened 2024-08-18 16:41 UTC
[Negfix8 script](https://sites.google.com/site/negfix/downloads)

**Comment by alibosworth** [comment] 2024-08-18 16:46
Thanks, duplicate of https://github.com/alibosworth/pakon-planar-raw-converter/issues/22

**Comment by alibosworth** [comment] 2024-08-18 16:46
Thanks Duplicate of https://github.com/alibosworth/pakon-planar-raw-converter/issues/22

**Closed as completed by alibosworth** 2024-08-18 16:46 UTC
